## Numpy 
Numpy is a commonly used library for the scientific use of python.
The package allows high-performance computation on multidimensional arrays. There are a lot of built-in functions for working with arrays. 
This notebook wants to show basic and advanced functionalities of numpy.

In [1]:
import numpy as np # importing numpy with an alias for easy use

Initializing arrays and accessing elements and information about a given array

In [2]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print(type(a)) # python built-in function for any python object
print(a.shape) # function of the numpy object that returns the shape of the array

print(a[0]) # access elements like in a python list

a[0] = 6 # change a list object value
print(a)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
[6 2 3 4 5]


Creating multidimensional arrays or matrices

In [3]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b.shape)
print(b[0, 0], b[1, 2])

(3, 3)
1 6


Convenience functions for easy array creation

In [4]:
a = np.zeros((3,3))
print(a)

b = np.ones((1, 2))
print(b)

c = np.eye(3) # creates a 3 dimensional identity matrix
print(c)

d = np.random.random((3,3)) #creates a 3x3 matrix with random values between 0 and 1
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.06229396 0.79582421 0.10601111]
 [0.71470154 0.94250043 0.8033633 ]
 [0.57177293 0.02279817 0.97473316]]


### Exercise 11.1
Create an array with shape (3,7) filled like
[[1, 2, 3 ,4 , 5, 6, 7]
 [8, 9, ...
 ]]

In [5]:
a = np.array([[1, 2, 3 ,4 , 5, 6, 7],
              [8, 9, 10, 11 ,12, 13, 14],
              [15, 16, 17, 18 ,19, 20, 21]
             ]
            )
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


### Exercise 11.2
Create an array that contains the elements from the last two rows from column three to five

In [6]:
b = a[-2:, 2:5]
print(b)

[[10 11 12]
 [17 18 19]]


Selecting and modifying elements from a matrix with lists

In [7]:
c = np.array([ 2, 3, 6])
#selects one elements from each row with the indices given by c
print(a[np.arange(3), c])
#add 10 to those elements
a[np.arange(3), c ] += 10
print(a)

[ 3 11 21]
[[ 1  2 13  4  5  6  7]
 [ 8  9 10 21 12 13 14]
 [15 16 17 18 19 20 31]]


### Exercise 11.3

Select the third, sixths and second element of row one, two and three from the array and multiply all elements by five

In [21]:
d = np.array([2, 5, 1])
a[np.arange(3), d] *=10
print(a)

[[   1    2  130  400    5    6    7]
 [   8    9   10   21   12  130 1400]
 [  15  160 1700   18   19   20   31]]


Boolean indexing and masks

In [9]:
mask = (a>9) #creates a boolean array where the element in a is larger than 9
print(mask)

print(a[mask]) #prints all values that fulfill the condition

print(a[a>2]) # in one line (very convenient for filtering data)

[[False False  True  True False False False]
 [False False  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
[ 13  40  10  21  12  13 140  15  16 170  18  19  20  31]
[ 13  40   5   6   7   8   9  10  21  12  13 140  15  16 170  18  19  20
  31]


## Datatypes in numpy

numpy chooses the datatype according to the values in the list.
A particular datatype can be enforced during initialization to avoid issues in calculations and assertions

In [10]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype=np.int8) #forces the datatype to be int8
print(x.dtype)

int64
float64
int8


## The useful stuff: Math with numpy arrays

numpy has a lot of built-in functionalities for basic maths

In [11]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = 2*np.eye(3)

#elementwise addition
print(x+y) 
print(np.add(x,y))
#elementwise subtraction
print(x-y) 
print(np.subtract(x,y))
#elementwise multiplication
print(x*y)
print(np.multiply(x,y))
#elementwise division
print(x/x)
print(np.divide(x,x))
#elementwise square root
print(np.sqrt(x))

[[ 3.  2.  3.]
 [ 4.  7.  6.]
 [ 7.  8. 11.]]
[[ 3.  2.  3.]
 [ 4.  7.  6.]
 [ 7.  8. 11.]]
[[-1.  2.  3.]
 [ 4.  3.  6.]
 [ 7.  8.  7.]]
[[-1.  2.  3.]
 [ 4.  3.  6.]
 [ 7.  8.  7.]]
[[ 2.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 18.]]
[[ 2.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 18.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [12]:
### Matrix multiplication

In [23]:

print(x.dot(y))
print(np.dot(x,y))
print(x@y) #this method is preferred in newer versions of numpy

print(np.cross(x, y)) #cross product of vectors (row wise)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[  0.   6.  -4.]
 [-12.   0.   8.]
 [ 16. -14.   0.]]


In [24]:
v = np.array([1, 2, 3]) #vector for matrix vector multiplication
w = np.array([4, 5, 6])
print(v.dot(w)) #scalar product
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x,v))
print(x@v)

print(np.cross(v,w)) # vector orthogonal to v, w

32
32
[14 32 50]
[14 32 50]
[14 32 50]
[-3  6 -3]


### more built-in functions

In [15]:
print(np.sum(x)) #sums up all elements
print(np.sum(x, axis=0)) #sums up all columns
print(np.sum(x, axis=1)) #sums up all rows

45
[12 15 18]
[ 6 15 24]


### Transposition


In [16]:
print(x)
print(x.T)
print(v)
print(v.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3]
[1 2 3]


### Broacasting and Reshaping
Broadcasting can be used to add a constant vector to every row or column of a matrix. Numpy handles these operation itself.

In [17]:
print(x)
print(v)
print(x + v) #this adds v elementwise to every column of x

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [18]:
z = np.array([1,2])
#outer product of vectors
# reshaping the v vector to a column-like vector 
print(np.reshape(v, (3,1)))
print(np.reshape(v, (3,1))* z)

[[1]
 [2]
 [3]]
[[1 2]
 [2 4]
 [3 6]]


## Using skimage for image processing
Images can be interpreted as matrices with RGB Values. These images can be read with skimage and other packages and be processed like numpy arrays.

In [19]:
from skimage import transform, io

img = io.imread('img/raccoon.jpg')
print(img.dtype, img.shape)
print(img)
img_tinted = img * [1, 0.8, 0.9] #changes the rgb values of the image
img_bw = np.dot(img[...,:3], [0.299, 0.587, 0.114]) #formula for greyscale conversion
print(img_bw)
img_resized = transform.resize(img, (200, 200), mode='symmetric', preserve_range=True) #resizes the image

io.imsave(arr=img_tinted, fname='img/raccoon_tinted.jpg')
io.imsave(arr=img_bw, fname='img/raccoon_bw.jpg')
io.imsave(arr=img_resized, fname='img/raccoon_resized.jpg')

uint8 (877, 1280, 3)
[[[185 157 146]
  [174 144 133]
  [174 141 124]
  ...
  [122 117 114]
  [124 119 116]
  [125 120 117]]

 [[184 157 146]
  [172 143 129]
  [173 140 123]
  ...
  [123 118 115]
  [124 119 116]
  [125 120 117]]

 [[180 154 141]
  [167 139 125]
  [169 138 120]
  ...
  [123 118 115]
  [124 119 116]
  [125 120 117]]

 ...

 [[135 131 132]
  [136 132 133]
  [136 132 133]
  ...
  [ 84  94  70]
  [ 86  96  72]
  [ 88  98  74]]

 [[138 134 135]
  [134 130 131]
  [134 130 131]
  ...
  [ 88  98  74]
  [ 91 101  76]
  [ 94 104  79]]

 [[143 139 140]
  [131 127 128]
  [130 126 127]
  ...
  [ 92 102  77]
  [ 95 105  80]
  [ 99 109  84]]]
[[164.118 151.716 148.929 ... 118.153 120.153 121.153]
 [163.819 150.075 147.929 ... 119.153 120.153 121.153]
 [160.292 145.776 145.217 ... 119.153 120.153 121.153]
 ...
 [132.31  133.31  133.31  ...  88.274  90.274  92.274]
 [135.31  131.31  131.31  ...  92.274  95.16   98.16 ]
 [140.31  128.31  127.31  ...  96.16   99.16  103.16 ]]


Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [3.499999999999659, 254.0]. Convert image to uint8 prior to saving to suppress this warning.
